# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('eng_name', models.CharField(default='', max_length=30)),
                ('hp', models.FloatField(default=0, max_length=10)),
                ('hpperlevel', models.FloatField(default=0, max_length=10)),
                ('hpmax', models.FloatField(default=0, max_length=10)),
                ('hpregen', models.FloatField(default=0, max_length=10)),
                ('hpregenperlevel', models.FloatField(default=0, max_length=10)),
                ('hpregenmax', models.FloatField(default=0, max_length=10)),
                ('mp', models.FloatField(default=0, max_length=10)),
                ('mpperlevel', models.FloatField(default=0, max_length=10)),
                ('mpmax', models.FloatField(default=0, max_length=10)),
                ('mpregen', models.FloatField(default=0, max_length=10)),
                ('mpregenperlevel', models.FloatField(default=0, max_length=10)),
                ('mpregenmax', models.FloatField(default=0, max_length=10)),
                ('movespeed', models.IntegerField(default=0)),
                ('attackdamage', models.FloatField(default=0, max_length=10)),
                ('attackdamageperlevel', models.FloatField(default=0, max_length=10)),
                ('attackdamagemax', models.FloatField(default=0, max_length=10)),
                ('attackspeed', models.FloatField(default=0, max_length=10)),
                ('attackspeedperlevel', models.FloatField(default=0, max_length=10)),
                ('attackrange', models.IntegerField(default=0)),
                ('armor', models.FloatField(default=0, max_length=10)),
                ('armorperlevel', models.FloatField(default=0, max_length=10)),
                ('armormax', models.FloatField(default=0, max_length=10)),
                ('spellblock', models.FloatField(default=0, max_length=10)),
                ('spellblockperlevel', models.FloatField(default=0, max_length=10)),
                ('spellblockmax', models.FloatField(default=0, max_length=10)),
                ('update_date', models.DateTimeField(verbose_name='update date')),
            ],
        ),
    ]
