# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='attackspeedmax',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
